name: ActionTrigger

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  UPLOAD_RELEASE: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 */3 * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Trigger Rockchip workflow
      run: |
        curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event_type": "Build-OpenWrts"}'

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        keep_minimum_runs: 1

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.4
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
          keep_latest: 10
          delete_tags: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
