name: Test wxPusher Notification

on:
  push:
    branches:
      - main  # 你可以根据需要修改为其他分支
  workflow_dispatch:  # 允许手动触发

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Send kernel version to wxPusher
      env:
        WXPUSHER_URL: 'https://wxpusher.zjiecode.com/api/send/message'
        WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}  # 使用 Secrets 存储 App Token
        WXPUSHER_USER_IDS: ${{ secrets.WXPUSHER_USER_IDS }}  # 使用 Secrets 存储 User IDs
        KERNEL_VERSION: '5.10.45'  # 可根据需要修改
      run: |
        curl -X POST $WXPUSHER_URL \
          -H "Content-Type: application/json" \
          -d '{
            "appToken": "'"$WXPUSHER_APP_TOKEN"'",
            "content": "内核版本: '"$KERNEL_VERSION"'",
            "summary": "OpenWrt 编译完成",
            "uids": '"$WXPUSHER_USER_IDS"'
          }'
