name: Test wxPusher Notification

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Send kernel version to wxPusher
      env:
        WXPUSHER_URL: 'https://wxpusher.zjiecode.com/api/send/message/'
        WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}  # 使用 Secrets 存储 App Token
        WXPUSHER_USER_IDS: ${{ secrets.WXPUSHER_USER_IDS }}  # 使用 Secrets 存储 User IDs
        KERNEL_VERSION: '5.10.45'  # 内核版本，可以替换为你想发送的内容
        SUMMARY: 'OpenWrt 编译完成'
      run: |
        # URL encode 对特殊字符进行编码
        ENCODED_CONTENT=$(echo "内核版本: $KERNEL_VERSION" | jq -sRr @uri)

        # 拼接 URL 和查询字符串，发送消息
        curl -X GET "$WXPUSHER_URL?appToken=$WXPUSHER_APP_TOKEN&content=$ENCODED_CONTENT&uid=$WXPUSHER_USER_IDS"
