name: Send Message via GET API

on:
  # 你可以根据需要设置触发条件
  push:
    branches:
      - main
  # 你也可以设置按时间间隔定时触发
  schedule:
    - cron: '0 9 * * *'  # 每天 9 点触发

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Send GET request via API
      run: |
        APP_TOKEN="AT_qHT0cTQfLwYOlBV9cJj9zDSyEmspsmyM"
        CONTENT="Hello World"
        UID="c1BcpqxEbD8irqlGUh9BhOqR2BvH8yWZ"
        URL="http%3a%2f%2fwxpusher.zjiecode.com"  # URL编码后的链接

        curl -G "https://wxpusher.zjiecode.com/api/send/message/" \
          --data-urlencode "appToken=${APP_TOKEN}" \
          --data-urlencode "content=${CONTENT}" \
          --data-urlencode "uid=${UID}" \
          --data-urlencode "url=${URL}"
