name: Send Message via GET API

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'  # 每天 9 点触发

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Send GET request via API
      env:
        WXPUSHER_URL: 'https://wxpusher.zjiecode.com/api/send/message'
        WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}  # 你的 WXPUSHER 应用 token
        WXPUSHER_USER_IDS: ${{ secrets.WXPUSHER_USER_IDS }}  # 你的用户 ID
      run: |
        # 设置要发送的消息内容
        CONTENT="123"
        URL="http%3a%2f%2fwxpusher.zjiecode.com"  # URL 编码后的链接

        # 打印 uid，检查是否正确传递
        echo "Sending message to UID: ${WXPUSHER_USER_IDS}"

        # 发送 GET 请求到指定用户
        curl -G "$WXPUSHER_URL" \
          --data-urlencode "appToken=${WXPUSHER_APP_TOKEN}" \
          --data-urlencode "content=${CONTENT}" \
          --data-urlencode "uid=${WXPUSHER_USER_IDS}" \
          --data-urlencode "url=${URL}"
