name: Send Kernel Version to wxPusher

on:
  push:
    branches:
      - main

jobs:
  send_kernel_version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Kernel Version
        run: |
          echo "KERNEL_VERSION=$(uname -r)" >> $GITHUB_ENV

      - name: Send kernel version to wxPusher
        env:
          WXPUSHER_URL: 'https://wxpusher.zjiecode.com/api/send/message'
          WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}
          WXPUSHER_USER_IDS: ${{ secrets.WXPUSHER_USER_IDS }}
        run: |
          CONTENT="内核版本: ${{ env.KERNEL_VERSION }}"
          URL="http%3a%2f%2fwxpusher.zjiecode.com"

          curl -G "$WXPUSHER_URL" \
            --data-urlencode "appToken=${WXPUSHER_APP_TOKEN}" \
            --data-urlencode "content=${CONTENT}" \
            --data-urlencode "uid=${WXPUSHER_USER_IDS}" \
            --data-urlencode "url=${URL}"
