name: Send Message via GET API

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'  # 每天 9 点触发

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Send kernel version to wxPusher
      if: steps.kernel_version.outputs.KERNEL_VERSION != ''
      run: |
        # 打印要发送的内容，检查变量是否正确
        echo "Sending kernel version: ${{ steps.kernel_version.outputs.KERNEL_VERSION }}"
        echo "App token: ${{ secrets.WXPUSHER_APP_TOKEN }}"

        # 发送 POST 请求
        curl -X POST ${{ env.WXPUSHER_URL }} \
          -d "app_token=${{ secrets.WXPUSHER_APP_TOKEN }}" \
          -d "content=内核版本: ${{ steps.kernel_version.outputs.KERNEL_VERSION }}" \
          -d "summary=OpenWrt 编译完成" \
          -d "uids=${{ secrets.WXPUSHER_USER_IDS }}"
